### ISSUE TITLE
运行roslaunch handsfree_hw handsfree_hw.launch 碰到一个新问题

### ISSUE THREAD

**Issue by nulidushuo** [HANDS-FREE/ROS_DEMO#13]
麻烦您帮忙看看，我应该从哪方面解决这个问题
![fedmzl h uz1 __ usxvpn](https://user-images.githubusercontent.com/30361061/46789806-00e77480-cd70-11e8-8f4f-63989dd8d5c3.jpg)

**Comment by foreverlms** [comment]
你是老版stone吗？
