### ISSUE TITLE
a little but critical bug in your code 

### ISSUE THREAD

**Issue by liao-zhihan** [HANDS-FREE/ROS_DEMO#2]
在transport_serial.cpp的52行缺少了
initialize_ok_ = true ;

**Comment by myyerrol** [comment]
@liao-zhihan I think you can propose **Pull requests** to fix this bug.

**Comment by xingE650** [comment]
i want to know where is the board.h included in handsfree_hw/include/sdk/hf_link/hf_link_platform.h
